
#- id: doi:10.1371/journal.pcbi.1007128
  #type: paper
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #date: 2020-12-4
  #image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  #buttons:
 #   - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open science
#    - collaboration
#  repo: greenelab/meta-review

# manually provide all citation details
- title: "LOHEN: Layer-wise Optimizations for Neural Network Inferences over Encrypted Data with High Performance or Accuracy"
  authors:
    - "**Kevin Nam**"
    - Youyeon Joo
    - Dongju Lee
    - Seungjin Ha
    - Hyunyoung Oh
    - Hyungon Moon<span>&#8224;</span>
    - Yunheung Paek<span>&#8224;</span>
  publisher: USENIX Security Symposium 2025 **(Usenix Security`25)**  <em style="color:#0000FF">KIISE S, BK21 IF 3</em>
  date: 2025-08-01
  image: images/papers/lohen.png
  link: https://www.usenix.org/conference/usenixsecurity25/presentation/nam-lohen
  tags:
    - Privacy Enhancing Techniques
    - Privacy Preserving AI

# manually provide all citation details
- title: "SLOTHE: Lazy Approximation of Non-Arithmetic Neural Network Functions over Encrypted Data"
  authors:
    - "**Kevin Nam**"
    - Youyeon Joo
    - Seungjin Ha
    - Yunheung Paek<span>&#8224;</span>
  publisher: USENIX Security Symposium 2025 **(Usenix Security`25)**  <em style="color:#0000FF">KIISE S, BK21 IF 3</em>
  date: 2025-08-01
  image: images/papers/slothe.png
  link: https://www.usenix.org/conference/usenixsecurity25/presentation/nam-slothe
  tags:
    - Privacy Enhancing Techniques
    - Privacy Preserving AI

# manually provide all citation details
- title: "An Accelerator for Low-computational Overhead Privacy-Preserving GNN Inference"
  authors:
    - Heonhui Jung
    - Whoiree Ha
    - "**Kevin Nam**"
    - Youyeon Joo
    - Lucas Oros
    - Yunheung Paek<span>&#8224;</span>
  publisher: The 32nd IEEE International Conference on High Performance Computing, Data, and Analytics 2025 **(HiPC `25)** <em style="color:#0000FF">BK21 IF 1</em>
  date: 2025-12-01
  image: images/papers/hipc.png
  #link: https://www.usenix.org/conference/usenixsecurity25/presentation/nam-slothe
  tags:
    - Hardware Accelerator
    - Privacy Preserving AI

- id:  doi:10.1145/3779212.3790170
- title: "HEPIC: Private Inference over Homomorphic Encryption with Client Intervention"
  authors:
    - "**Kevin Nam**"
    - Youyeon Joo
    - Seungjin Ha
    - Hyungon Moon<span>&#8224;</span>
    - Yunheung Paek<span>&#8224;</span>
  publisher: The 31st ACM International Conference on Architectural Support for Programming Languages and Operating Systems 2026 **(ASPLOS `26)**  <em style="color:#0000FF">KIISE S, BK21 IF 4</em>
  date: 2026-03-22
  image: images/papers/hepic.png
  link: https://doi.org/hbsghf
  tags:
    - Privacy Enhancing Techniques
    - Privacy Preserving AI

- id:  doi:10.1145/3676641.3716246
  title: "Affinity-based Optimizations for TFHE on Processing-in-DRAM"
  authors:
    - "**Kevin Nam**"
    - Heonhui Jung
    - Hyunyoung Oh<span>&#8224;</span>
    - Yunheung Paek<span>&#8224;</span>
  publisher: The 30th ACM International Conference on Architectural Support for Programming Languages and Operating Systems 2025 **(ASPLOS `25)**  <em style="color:#0000FF">KIISE S, BK21 IF 4</em>
  date: 2025-04-01
  image: images/papers/theim.png
  link: https://dl.acm.org/doi/10.1145/3676641.3716246
  tags:
    - Hardware Accelerator
    - Privacy Enhancing Techniques

- id: doi:10.1007/978-3-031-37111-0_14
  title: "Area-Efficient Accelerator for the Full NTRU-KEM Algorithm"
  authors:
    - Yongseok Lee
    - "**Kevin Nam**"
    - Youyeon Joo
    - Jihwan Kim
    - Hyunyoung Oh<span>&#8224;</span>
    - Yunheung Paek<span>&#8224;</span>
  publisher: The International Conference on Computational Science and Its Applications, 2023
  date: 2023-04-01
  image: images/papers/ntru.png
  link: https://scholarworks.bwise.kr/gachon/bitstream/2020.sw.gachon/92307/1/_ICCSA2023__NTRU.pdf
  tags:
    - Hardware Accelerator
    - Post-Quantum Cryptography

- id: doi:10.1145/3508352.3549413
  title: "Accelerating N-bit Operations over TFHE on Commodity CPU-FPGA"
  authors:
    - "**Kevin Nam**"
    - Hyunyoung Oh
    - Hyungon Moon<span>&#8224;</span>
    - Yunheung Paek<span>&#8224;</span>
  publisher: IEEE/ACM International Conference on Computer-Aided Design **(ICCAD `222)**  <em style="color:#0000FF">KIISE A, BK21 IF 3</em>
  date: 2022-10-01
  image: images/papers/xhec.png
  link: doi.org/10.1145/3508352.3549413
  tags:
    - Hardware Acceleration
    - Privacy Enhancing Techniques

- id: doi:10.1109/ACCESS.2024.3387489
  title: "An Efficient Hardware/Software Co-design for FALCON on Low-End Embedded Systems"
  authors:
    - Yongseok Lee
    - Jonghee Youn
    - "**Kevin Nam**"
    - Heonhui Jung
    - Myunghyun Cho
    - Jinmyung Na
    - Jong-Yeon Park
    - Seungsu Jeon
    - Bogyeong Kang
    - Hyunyoung Oh<span>&#8224;</span>
    - Yunheung Paek<span>&#8224;</span>
  publisher: IEEE Access
  date: 2024-10-01
  image: images/papers/falcon.png
  link: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10496572
  tags:
    - hardware security
    - Post-Quantum Cryptography

- id: doi:10.1109/ACCESS.2021.3069223
  title: "MeetGo: A trusted execution environment for remote applications on FPGA"
  authors:
    - Hyungyoung Oh
    - "**Kevin Nam**"
    - Seongil Jeon
    - Yeongpil Cho<span>&#8224;</span>
    - Yunheung Paek<span>&#8224;</span>
  publisher: IEEE Access
  date: 2021-10-01
  image: images/papers/meetgo.png
  link: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9388667
  tags:
    - hardware security
    - Trusted Execution Environment

- id: doi:10.1109/ACCESS.2026.3701023
  title: "PCPSI: Efficient Unbalanced Private Set Intersection Using Homomorphic Encryption With Plaintext Ciphertext Multiplication"
  authors:
  - Dongju Lee
  - Sungyeon Lee
  - Youyeon Joo
  - "**Kevin Nam<span>&#8224;</span>**"
  - Yunheung Paek<span>&#8224;</span>
  publisher: IEEE Access
  date: '2026-01-01'
  link: https://doi.org/hb8m6m
  orcid: 0000-0002-4621-2434
  plugin: orcid.py
  file: orcid.yaml